// AskSAV Mobile v0.1
import { SafeAreaView,StyleSheet,Text,TouchableOpacity,View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
export default function HomeScreen(){return <SafeAreaView style={s.safe}><View style={s.page}>
<View style={s.brandRow}><View style={s.logo}><Text style={s.logoText}>SAV</Text></View><View><Text style={s.brand}>AskSAV</Text><Text style={s.brandSub}>Visual Intelligence</Text></View></View>
<View style={s.hero}><Text style={s.eyebrow}>SEE IT. KNOW IT. VALUE IT.</Text><Text style={s.title}>What have you got?</Text><Text style={s.subtitle}>Take a photo of almost anything. AskSAV helps identify it, assess visible condition and understand its value.</Text></View>
<View style={s.card}><View style={s.camera}><Ionicons name="camera-outline" size={42} color="#087f72"/></View><Text style={s.cardTitle}>Analyse an item</Text><Text style={s.copy}>Start with a clear photo of the item you want to understand.</Text>
<TouchableOpacity style={s.primary}><Ionicons name="camera" size={20} color="#fff"/><Text style={s.primaryText}>Take a photo</Text></TouchableOpacity>
<TouchableOpacity style={s.secondary}><Ionicons name="images-outline" size={20} color="#087f72"/><Text style={s.secondaryText}>Choose from photos</Text></TouchableOpacity></View>
<Text style={s.note}>Camera and photo-library actions arrive in AskSAV Mobile v0.2.</Text>
</View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#f4fbf9"},page:{flex:1,paddingHorizontal:22,paddingTop:16},brandRow:{flexDirection:"row",alignItems:"center",gap:11},logo:{width:48,height:48,borderRadius:15,backgroundColor:"#13b8aa",alignItems:"center",justifyContent:"center"},logoText:{color:"#fff",fontWeight:"900",fontSize:16},brand:{color:"#082f49",fontSize:24,fontWeight:"900"},brandSub:{color:"#66858d",fontSize:11},hero:{marginTop:38},eyebrow:{color:"#0a9b80",fontSize:12,fontWeight:"900",letterSpacing:1.2},title:{color:"#062f4f",fontSize:38,lineHeight:43,fontWeight:"900",marginTop:8},subtitle:{color:"#4f6f7b",fontSize:16,lineHeight:24,marginTop:12},card:{backgroundColor:"#fff",borderRadius:26,padding:24,marginTop:30,borderWidth:1,borderColor:"#d9ebe7",shadowColor:"#000",shadowOpacity:.06,shadowRadius:18,shadowOffset:{width:0,height:8},elevation:3},camera:{width:78,height:78,borderRadius:39,backgroundColor:"#e7f8f4",alignItems:"center",justifyContent:"center",alignSelf:"center"},cardTitle:{color:"#062f4f",fontSize:25,fontWeight:"900",textAlign:"center",marginTop:18},copy:{color:"#67818a",fontSize:14,lineHeight:21,textAlign:"center",marginTop:7,marginBottom:22},primary:{minHeight:56,borderRadius:16,backgroundColor:"#0aaf86",flexDirection:"row",gap:9,alignItems:"center",justifyContent:"center"},primaryText:{color:"#fff",fontSize:16,fontWeight:"900"},secondary:{minHeight:54,borderRadius:16,marginTop:11,borderWidth:1,borderColor:"#b9ddd5",flexDirection:"row",gap:9,alignItems:"center",justifyContent:"center"},secondaryText:{color:"#087f72",fontSize:15,fontWeight:"800"},note:{color:"#7b9198",fontSize:11,textAlign:"center",marginTop:18}});